### ISSUE TITLE
Mapping external services

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#118]
假定一个场景，我们的 K8s 集群中部署的都是业务服务，而我们的 DB 使用的是云厂商的 MySQL，这个时候要怎么让我们的业务服务连上 MySQL 呢？通常的做法是把 DB 信息（IP、Port）写在配置文件中让业务程序去读取，这样子做是可行的，但有一些弊端，比如：

1. 业务代码要写读取配置文件的逻辑
2. 如果数据库 IP、Port 变了，那么就要重启业务服务重新读取配置

对于此种问题，我们可以通过灵活使用 K8s Service 来解决。通常情况下，我们创建 Service 的时候会加上 `selector` ，用以标识请求到该 Service 的流量要转到哪一个 Pod。其实，背后会有一个叫 Endpoints 的资源被自动创建，其标明了 Pod 的地址信息，比如：

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: auditmanager
subsets:
- addresses:
  - ip: 10.244.2.91
  ports:
  - port: 8081
    protocol: TCP
```

其中，Endpoints 的 name 与 Service 一致，该名字也会被注册到 DNS 中。

为了访问集群外部的 MySQL，我们可以创建一个没有 `selector` 的 Serivice，然后创建一个**同名的 Endpoints**，在 Endpoints 中写明 MySQL 的 IP & Port，这样子集群内的服务就可以使用 DNS 机制来访问 MySQL 了。如果后续 MySQL 地址信息有变，也仅需改变 Endpoints 配置即可，业务代码无需改动，示例如下：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: xmai-manager
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306

---

kind: Endpoints
apiVersion: v1
metadata:
  namespace: xmai-manager
  name: db
subsets:
- addresses:
  - ip: 192.168.1.105
  ports:
  - port: 3306
```
