### ISSUE TITLE
K8s namespace 之 “金钟罩”

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#120]
## 需求场景

在实际开发中有这样一类需求：K8s 集群新加入了几个节点，

1. 只有特定 namespace 的服务可以调度到这几个 Node 上，也必须调度到这几个 Node 上
2. 其他 namespace 的服务不允许调度到这几个 Node 上

**这就相当于需要给几个固定的 Node 罩了一层 “金钟罩”，只允许特定 namespace 的服务使用。**

### 1. 调度到指定节点

其实实施起来还是很简单的，“调度到特定节点” 可以通过添加 `NodeSelector` 来实现，当然首先要为节点打标签。

为节点打标签

```
kubectl label node 192-168-1-133 type=manager
```

添加 `nodeSelector` 配置，把服务调度到指定节点

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    type: manager
```

### 2. 不允许其他服务调度

K8s 设计了 `taint` 特性，实现不允许其他服务调度到特定 Node，需要调度到这些节点上的服务要加上 `toleration` 配置。

为节点标记 taint

```console
kubectl taint nodes 192-168-1-133 type=manager:NoSchedule
```

在 Pod 中声明 toleration

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "manager"
    effect: "NoSchedule"
```

## 更优雅的解决

在 YAML 0 改动的前提下，如何满足这样的场景？apiserver 有自动为特定 namespace 服务添加 `NodeSelector` 、`tolerations` 的 controllers 。

打开 `/etc/kubernetes/manifests/kube-apiserver.yaml` 找到 `--enable-admission-plugins` ，添加 `PodNodeSelector`、`PodTolerationRestriction`，`:wq` 后 kube-apiserver 会自动重启生效。接着，我们为 namespace 添加 `annotations` 让该 namespace 的 Pod 自动添加 `NodeSeletor` & `tolerations`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "type", "Operator":
      "Equal", "Value": "manager", "Effect": "NoSchedule"}]'
    scheduler.alpha.kubernetes.io/node-selector: type=manager
  name: xmai-manager
```

这样就不需要一个个做 YAML 改造了。
