### ISSUE TITLE
K8s auth 机制中 impersonation 学习

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#190]
“impersonation 机制” 一句话来讲就是：允许一个 subject（User、Group、ServiceAccount） 去模拟另外一个 subject。K8s RBAC 支持通过 `impersonate` verb 来实现对 "users", "groups", "serviceaccounts" 的模拟。当 A 模拟 B 执行操作时，其将使用 B 的权限集合。

## impersonation 机制的价值是什么？

1. 实现类似 `linux sudo` 能力，针对普通用户做 “短暂提权”（而不是直接授予权限），并且该行为可以被审计到
2. admin 通过模拟特定用户，来 debug 授权策略

## impersonation 的流程及原理

client 端可以通过添加 HTTP header `Impersonate-User`、`Impersonate-Group` 等来模拟指定的 User 或 Group。

当 client 带着 `Impersonate-*` HTTP header 以及其凭证请求后，apiserver 将：

1. 认证 client 端凭证
2. 确保请求的 User 具有模拟目标对象的权限
3. 请求体中 user 信息被替换为模拟对象的信息
4. 通过模拟对象的权限，来评估操作是否可以被执行

### 背景与需求

默认场景下，`ops-team` 仅有查看集群信息的权限，在一些特殊需求下，可以执行提权做新增、编辑和删除。

### 实现与验证

首先创建一个 ClusterRoleBinding，授予 Group ops-team 集群级别的 View 权限。这样 ops-team 可以查看任何资源状态，但无权新增、修改和删除。

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ops-team
```

接着创建 ClusterRoleBinding，使 User cluster-admin 绑定 ClusterRole cluster-admin(集群管理员) 权限。（这里不能为 ops-team 直接绑定 cluster-admin 权限，不然 ops-team 就直接具有了 cluster-admin 权限，无需再提权了）

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cluster-admin
```

然后创建可以模拟 User cluster-admin 的 ClusterRole，并将其通过 ClusterRoleBinding 与 ops-team 绑定。

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-impersonator
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: ["cluster-admin"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-impersonate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-impersonator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ops-team
```

接着我们使用 ops-team Group 的 kubeconfig(**证书中 CN=steve,O=ops-team**) 来测试 impersonation，以 default namespace 下的 SA 为例，我们发现：ops-team 默认具备查看 SA 的权限，但无法创建新的 SA，通过添加 `--as=cluster-admin` 模拟为 cluster-admin User 后，可以创建 SA 成功。

```console
$ kubectl get sa -n default

NAME      SECRETS   AGE
default   1         30h

$ kubectl create sa foo -n default
error: failed to create serviceaccount: serviceaccounts is forbidden: User "steve" cannot create resource "serviceaccounts" in API group "" in the namespace "default"

$ kubectl create sa foo -n default --as=cluster-admin
serviceaccount/foo created

$ kubectl get sa -n default
NAME      SECRETS   AGE
default   1         30h
foo       1         14s
```

最后，还有几个小提示：

1. **impersonation 一定要用 ClusterRole、ClusterRoleBinding**。因为模拟 User（包括任意 namespace 的 ServiceAccount）、Group 后，将具备目标对象的所有权限，所以模拟行为是集群级别的。
2. 使用 kubectl `--as` 参数模拟 ServiceAccount 时，要使用 `system:serviceaccount:<NAMESPACE>:<NAME>` 格式

## 参考文档

- [Least Privilege in Kubernetes Using Impersonation](https://johnharris.io/2019/08/least-privilege-in-kubernetes-using-impersonation/)
- [https://www.redhat.com/sysadmin/sudo-kubernetes](https://www.redhat.com/sysadmin/sudo-kubernetes)
- [Simplify Kubernetes Resource Access Control using RBAC Impersonation](https://docs.bitnami.com/tutorials/simplify-kubernetes-resource-access-rbac-impersonation/)
- [Authenticating](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)
