### ISSUE TITLE
k8s 之 ConfigMap 探究

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#56]
ConfigMap 可以理解为 k8s 生态中的 **配置文件**，它使得 Image & configuration 脱钩解耦合。ConfigMap 在使用上有如下限制：

1. ConfigMap 归属于特定的 namespace，它只能被该 namespace 下的 Pod 所使用。
2. 假使 Pod 引用的 ConfigMap 未被创建或者应用的 ConfigMap Key 未存在，Pod 将启动失败。

### ConfigMap 创建的几个方法

**1. 直接通过目录创建**

`--from-file` 后接一个目录，则创建的 ConfigMap 中 Key 为文件名，Value 为文件内容。

```
kubectl create configmap game-config --from-file=configure-pod-container/configmap/
```

**2. 通过文件创建**

`--from-file` 后面可以接文件，并且 `--from-file` 参数可以使用多次。`--from-file=<my-key-name>=<path-to-file>` 可以修改掉默认的文件名作为 KEY。

`--from-env-file` 选项可以从环境变量文件创建 ConfigMap。该选项只能使用一次，**使用多次的话，后边的将会覆盖前面的。**

```
kubectl create configmap game-config-2 --from-file=configure-pod-container/configmap/game.properties --from-file=configure-pod-container/configmap/ui.properties
```

**3. 通过字面量创建**

`--from-literal` 后接 **KEY=VALUE**，`--from-literal` 可以使用多次

```
kubectl create configmap special-config --from-literal=special.how=very --from-literal=special.type=charm
```

### ConfigMap 挂载到 Volume

**1. 将 ConfigMap 中保存的文件挂载到指定目录**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
  restartPolicy: Never
```

**2. 指明 ConfigMap 中文件的挂载路径**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/config/keys" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: SPECIAL_LEVEL
          # 指定某个配置文件的路径
          path: keys 
  restartPolicy: Never
```
