### ISSUE TITLE
让 k8s 集群支持 TTLAfterFinished

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#78]
### 支持 TTLAfterFinished 有什么用？

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-ttl
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

如 YAML 所示，`ttlSecondsAfterFinished` 可以让 Job 在结束（无论是失败还是正常完成）后 100s 自动删除。清理掉 Job 记录，减轻 etcd 的存储负担。

### 如何操作？

需要在 kube-apiserver、kube-controller-manager **--feature-gates** 对该功能做开启。

1. 其中参数要加上 `--feature-gates=TTLAfterFinished=true`
2. 加载新的 sytemctl 配置 `systemctl daemon-reload`
3. 重启  kube-apiserver & kube-controller-manager `systemctl restart kube-apiserver kube-controller-manager`
