### ISSUE TITLE
限定用户访问特定 namespace

### ISSUE THREAD

**Issue by Wang-Kai** [Wang-Kai/cherish-today#84]
### 关于 `kubeconfig`

`kubeconfig` 是 `kubectl` 访问 k8s 集群所需要的配置文件，其中主要包括如下信息：

1. 验证 `kube-apiserver` 的 CA 根证书
2. 标识管理员身份的 `证书 & 私钥`，或者标识普通用户的 `token`

本文主要针对场景是：**为一个特定用户授予特定 `namespace` 的操作权限**。

##### 1. 创建要访问的 `namespace`

```
kubectl create ns mynamespace
```

##### 2. 创建 sa 并为其授予必要权限

创建 `ServiceAccount`、`Role`、`RoleBinding`，其中 `Role` 包含了要授予的权限，`RoleBinding` 将 `Role` 中定义的权限赋予给 `ServiceAccount`。

```yaml
# 创建 service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mynamespace-user
  namespace: mynamespace

# 创建 Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mynamespace-user-full-access
  namespace: mynamespace
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
  
# 角色绑定  
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mynamespace-user-view
  namespace: mynamespace
subjects:
- kind: ServiceAccount
  name: mynamespace-user
  namespace: mynamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mynamespace-user-full-access
```

##### 3. 获取根证书 & sa `Token`

`kubectl` & `kube-apiserver` 之间是通信是 HTTPS 双向认证，所以 `kubeconfig` 中要求填写 CA 证书。`token` 是 `api-server` 用来鉴权 kubectl 的凭证。

创建 `sa` 的同时 `kube-controller-manager` 会顺带创建一个 `secret` 来存储 `sa` 的 `token`。可以通过 `kubectl get secret -n mynamespace` 来找到 ` mynamespace-user` 对应的 Token。

```
# 获取 sa token
kubectl  get secrets  -n mynamespace mynamespace-user-token-g7c89   -o "jsonpath={.data.token}"

# 获取 CA 根证书
kubectl  get secrets  -n mynamespace mynamespace-user-token-g7c89  -o "jsonpath={.data.ca\.crt}"
```

##### 4. 填充 `kubeconfig`

```yaml
apiVersion: v1
kind: Config
preferences: {}

# Define the cluster
clusters:
- cluster:
    certificate-authority-data: PLACE CERTIFICATE HERE
    # You'll need the API endpoint of your Cluster here:
    server: https://YOUR_KUBERNETES_API_ENDPOINT
  name: my-cluster

# Define the user
users:
- name: mynamespace-user
  user:
    token: PLACE USER TOKEN HERE

# Define the context: linking a user to a cluster
contexts:
- context:
    cluster: my-cluster
    namespace: mynamespace
    user: mynamespace-user
  name: mynamespace

# Define current context
current-context: mynamespace
```

### 开始使用

`kubectl` 会通过如下途径依次去找 `kubeconfig` 文件，直到找到为止。定位到了 `kubeconfig` 文件后，`kubectl` 将会使用其中参数去访问 `kube-apiserver`。

**一、使用 KUBECONFIG 环境变量**

默认的，kubectl 会使用 `KUBECONFIG` 环境变量所指向的 `kubeconfig` 配置文件

**二、默认的配置文件地址**

如果 `KUBECONFIG` 不存在，kubectl 默认会去找 `$HOME/.kube/config` 

**三、使用 `--kubeconfig`**

如果 `--kubeconfig` 参数被指定，那么将会使用所指定的配置文件
